### PR TITLE
List repeated visits to a url separately (toggleable)

### PR DESCRIPTION
**Pull request by Felicis**
Hi, 
I have always been super annoyed about firefox showing only the latest visit to a url in the history and no config option to change this (e.g. when you go through your history to look for something and open an entry and it disappears from the history, because it gets pushed to the top; and it also autoscrolls to the top because of this). 
Fortunately firefox does internally save every time a url was visited, accessible from the history api for addons. Since I like your addon very much (imo by far the best vanilla history alternative), and your source code is on github, I decided to mod it and add the possibility to show every separate visit to a url. 

I did this just for myself, but if you like it, you can integrate it in you addon.
(It has a toggle button and is disabled by default)

### CODE REVIEW

**Comment by Vincent-P** [comment]
Hello, thanks for you pull request!
There are a lot of changes and commit, can you please make a summary of what you changed and why?
It also seems that git is not configured correctly on your machine, the author of your commits is "Your Name".
Here is the documentation on how to setup git correctly https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup

**Comment by ladevieq** [comment]
Hey man, thanks for the PR.

It's a great job but it would be nice to display duplicated entries by considering the time it was searched at instead of displaying all the entries side by side.

**Comment by Felicis** [comment]
I just set the author to my github username and email.
(It is actually not a mistake, but I have anonymized my global git username and email, because I don't like accidentally publishing my real name and email by pushing a repo where I committed.)
I also fixed a small bug.

**Comment by Felicis** [comment]
### Short summary
In the history screen there is now a toggleable button (icons for button added) to activate the "repeated visits" feature. The state of the button is saved in storage, just like the current view (day/week/month). When repeated visits are active, the history contains an entry for every single visit to a url, not just the latest (default behaviour). The single visit times are extracted from the history by using the `browser.history.getVisits({url})` function on every url. The returned object has the property `visitTime`, which is optional in firefox, but seems to contain different times for each visit (on my linux machine). If `visitTime` is not defined for a visit, it be dropped silently.

**Comment by Felicis** [comment]
### Detailed changes:
#### app.js
* `this.state` has a new property, called `repeatedVisits`, which is by default `false`
* the `React.Component` has a new button with an icon label, which shows the current state of the button (slashed squares => disabled)
* clicking the button calls the new `toggleRepeatedVisits` function, which toggles `this.state.repeatedVisits`, stores the new value to local storage and reloads the view with the new state (reloads on every hit, activation and deactivation)
* HistoryApi.getDayVisits/getWeekVisits/getMonthVisits are passed the `repeatedVisits` state as an additional parameter 
#### history-api.js
* if `repeatedVisits` is true:
  * the history has to be searched _until the current time_, since `HistoryItem`s are matched by their `lastVisitTime` property
  * for each found `HistoryItem`, all visits (`VisitItem`s) are retrieved
  * visits are kept if the property `.visitTime` is defined and if the `visitTime` is in range of the currently selected time range in the view
  * for every kept visit a new `HistoryItem` object is created with `.lastVisitTime` set the `.visitTime` of the visit (url and title copied from parent `HistoryItem`)
  * all kept visits are returned to be displayed in the view
* if `repeatedVisits` is false:
  * _the original code without changes_
#### index.js
* retrieve `repeatedVisits` value from storage, when loading, and pass it to the app

**Comment by Felicis** [comment]
I hope the detail is sufficient and the code understandable. If you have any questions about the code, don't hesitate to ask. Also I hope I added enough comments in the code.

**Comment by Felicis** [comment]
> [...] but it would be nice to display duplicated entries by considering the time it was visited at instead of displaying all the entries side by side.

I don't quite understand what you mean. The duplicated entries (repeated visits) are displayed with the exact time when they were visited. The time of the repeat visit, not of the latest visit. Also since the latest visit is essentially a repeated visit, they are not handled separately: Everything is just a visit, either with repeat siblings or not.
Or do you mean that the unique visits should be marked in some way to differentiate them from the repeated visits? So when you hit the button you see which visits have duplicates in the list?

**Comment by Vincent-P** [comment]
Never mind it is fine, I will merge the PR tomorrow.
Thanks for your contribution!

**Comment by Vincent-P** [comment]
In fact, the weekly (and monthly) view seems incorrect:
In the day view, the repeat visits are correctly sorted by time of visit.
But in the weekly view, it seems that all repeated visits are next to each other in the list and therefore not sorted.

**Comment by Felicis** [comment]
I just checked on the weeks and I don't see that they are not sorted correctly by the visit time. I did however find a bug in the weekly view in both my and your implementation :joy: 
I don't filter repeat visits to match the time range, and you add entries to the weekday of their last visit, not the matched visit.

**Comment by Felicis** [comment]
The entry is added to the weekday, which matches its latest visit (Thursday, April 22, 2021):
image
But the actual visits in that week (which are why it is returned by history.search() in the first place) happened on Tuesday 6th and Friday 9th:
image

**Comment by Felicis** [comment]
I think this could be fixed, by searching the history multiple times and storing the results separately, but the time of day will still be incorrect, since it uses the `lastVisitTime` and not the actual time for the old visit.

**Comment by Felicis** [comment]
Also could you send me a picture of the incorrect views you found?

**Comment by Vincent-P** [comment]
Sure, here is my history from yesterday.
On the day view, the "web-ext - Google Search" page is correctly displayed, that is 5 times at 8:20 and 1 time at 8:11.
However in the week view all of the visits are displayed together.

week
day

**Comment by Felicis** [comment]
Good call :+1: The entries were actually never being sorted for the weeks and months! Should be fixed now.

**Pull request merged**
